### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by MozzVader** [maker-dude/EpicZones#11]
Hi, I'm having this issue with permissions.
I set the Zone and then deny the "build" and "destroy" perms to the "user" group but nothing happens.

I looked for the solution everywhere but I couldn't make it work.
- What steps will reproduce the problem?
  Get in the game and set the zone
  /zone perm user build deny
  /zone perm user destroy deny
  login as a player in the denied group (no OP, no Admin) and place blocks
- What is the expected output? What do you see instead?
  Players in the "user" group shouldn't be able to build inside the zone, but they can
  No error message at any time. The zone exists (you can see the enter and exit message) but then, the perms are completly ignored
- What version of the product are you using?
  0.37
- Please provide any additional information below.
  I tried writing "epiczones.ignorepermissions = false" on the banned group and nothing happened (not sure if using it correctly, also tried the "true" flag)
-  Here you can download all the needed files (permissions folder an .jar / startup log / EpicZones folder and .jar)

https://rapidshare.com/files/2823390265/files.rar

thank you in advance

**Comment by CourtArtanis** [comment]
Hi,

What permissions system are you using?

From: MozzVader 
Sent: Wednesday, September 19, 2012 5:57 AM
To: RandomAppDev/EpicZones 
Subject: [EpicZones] Permissions not working (#11)

Hi, I'm having this issue with permissions.
I set the Zone and then deny the "build" and "destroy" perms to the "user" group but nothing happens.

I looked for the solution everywhere but I couldn't make it work.

  a.. What steps will reproduce the problem?
  Get in the game and set the zone
  /zone perm user build deny
  /zone perm user destroy deny
  login as a player in the denied group (no OP, no Admin) and place blocks

  b.. What is the expected output? What do you see instead?
  Players in the "user" group shouldn't be able to build inside the zone, but they can
  No error message at any time. The zone exists (you can see the enter and exit message) but then, the perms are completly ignored

  c.. What version of the product are you using?
  0.37

  d.. Please provide any additional information below.
  I tried writing "epiczones.ignorepermissions = false" on the banned group and nothing happened (not sure if using it correctly, also tried the "true" flag)

  e.. Here you can download all the needed files (permissions folder an .jar / startup log / EpicZones folder and .jar)

https://rapidshare.com/files/2823390265/files.rar

thank you in advance

**Comment by MozzVader** [comment]
Thank you CourtArtanis!!!

I'm using Permissions Bukkit 2.0 and it is updated, sorry (http://dev.bukkit.org/server-mods/permbukkit/)

Kind regards!

**Comment by CourtArtanis** [comment]
Could you do me a really big favour? 
If this is possible for you:

1) Backup your server
2) Remove PermsBukkit
3) Install PermissionsEX (PEX) or bPerms (I prefer PEX personally)
4) Just run a test setup, one group with epiczones.\* and one group without any EZ perms at all, see if the zones still ignore perms.
5) Inform me of results 

This will help us deduce a problem between perms > Epiczones or Epiczones > Perms or even just perms system itself.

Thanks

**Comment by MozzVader** [comment]
I must be doing somethig wrong.
I've created a whole new server... the only plugins are PEX and EpicZonez... still not working.

It doesn't matter what group the user is in, everytime it can change blocks.

there are the same files but for this new server
https://rapidshare.com/files/607018155/newserver.rar

thank you!

**Comment by CourtArtanis** [comment]
Look in permissions config.

groups:
  default:
    default: true
    permissions:
    - -modifyworld.*
    - epiczones.*

The default group has epiczones.\* – any group with this node will have full permissions, ignoring zone based permissions as well 
It’s an admin node and shouldn’t be given to any non mod/admin player.

**Comment by MozzVader** [comment]
Well... it didn't work.
Also... Anyone can destroy any block, even the "default" group which has the "- -modifyworld.*" node.
So I'm thinking the PEX plugin is not working (since it is not updated) or I'm just too stupid to make it work XDD
It's a shame because this plugin seems really good and it works for a lot of people LOL (but me)
Thank you for your help and keep the good work, pal!

**Comment by CourtArtanis** [comment]
I have PEX on my production server and it works perfectly, so there must be something in your config which still isn’t right.

Do you have “modifyworld.jar” installed as well as Pex? You need them both in order to use modifyworld nodes.

**Comment by MozzVader** [comment]
Ohhhhh... that's right. Well, I fixed the modifyworld thing...
But it keeps ignoring the EpicZones
The perms file is the same:

groups:
  default:
    default: true
    permissions:
    - -modifyworld.*
  usera:
    permissions:
    - modifyworld.*
    - epiczones.*
  userb:
    permissions:
    - modifyworld.*
users:
    Mozz_Vader:
        group:
        - usera <--- It doesn't matter the group

Now I really feel I'm wasting your time... sorry :P

**Comment by MozzVader** [comment]
Also... the one with "- epiczones.*" does not have "epiczones.admin=true"
So i think it doesn't get the node at all

Using the node "- -epiczones.ignorepermissions" doesn't help either

**Comment by CourtArtanis** [comment]
No, “- epiczones.*” gives you every single node for EpicZones – It’s an Admin node and should not be in your player groups.
- epiczones.\* will give you epiczones.admin for the group it’s in.

**Comment by CourtArtanis** [comment]
Ok, the default group can still break blocks yes? Even with modifyworld?

**Comment by MozzVader** [comment]
Oh sorry... I thought that was the way you are supposed to negate access.
like it was a false

**Comment by MozzVader** [comment]
Could you send me how you would write that file? I mean the permissions one

**Comment by CourtArtanis** [comment]
groups:
  default: (This is the default guests group the server auto-assigns to new players)
    default: true
    build: false
    permissions:
    - modifyworld.chat
As you can see in this group ABOVE, there is only 1 node – modifyworld.chat
By default, all nodes are negated unless otherwise specified. The server will ONLY assign the nodes you input and negate the rest automatically, this works for ALL plugins and for all Permissions.x based systems (I use PEX)

  builder:
    default: false
    build: true 
    permissions:
- modifyworld.\* (The .\* node means the server will look for every node starting with modifyworld [or other plugin prefix]. This works with 99% of plugins)
- other.nodes.here
- and.here
  Above, please note the modifyworld.\* – Modifyworld is safe to give the \* wildcard to all registered players, because all it does is moderate player actions within the world (Breaking and placing certain blocks etc and using chat). For most other plugins, please check the documentation to make sure you arn’t giving nodes that players could use to damage your world! (Ie. Administrative and Operator nodes)

admin:
    default: false
    build: true
    permissions:
    - ‘_’
Above, This is an Operator setup. The ‘_’ node basically signifies that players in that group have full and total access or control for every single plugin on the server, This is a decent setup unless you want to moderate the access your Administrators have, which is sometimes the case. This node generally should only be given to people you 100% know and trust, or even just the Owner of the server. Sometimes, this isn’t convenient because some plugins require certain nodes to be present in order to function as the player intended (like certain types of RPG plugins and EpicZones). Please bear in mind, if the Operator node (‘*’) is present – the server will ignore ALL OTHER NODES inside that group.
If you have this setup, you will ignore all zone based permissions in every single zone and have full unregulated access to the world.

Personally, i prefer the next approach – It may be a bit more long winded as it requires using regular expressions or adding wildcard nodes for each plugin you install.

admin
    default: false
    build: true
    permissions:
- -epiczones.ignorepermissions (Always negate nodes BEFORE the plugin you are negating for, as seen here)
  - epiczones.*
- modifyworld.*
- random.*
- other.*
- plugins.*

As above, you’ll notice the negated “epiczones.ignorepermissions” node is BEFORE epiczones.\* – This is important and if you negate after epiczones.\* (The same for any plugin in fact) it will not work. This is because the server looks through this config line by line and executes the actions in turn. If you negate a node, it will tell the server to ignore that node indefinately until the config is changed. IF you put the wildcard “epiczones.*” before the negation “-epiczones.ignorepermissions” – It will tell the server to include all nodes for that plugin and will skip the negation on the next line, thus making it ineffective.

As a general rule, i personally always put the negated nodes for all plugins at the top of the perms list for that group. That way you know they will be read 

I hope this was in-depth enough for you  I may even add this to our Wiki lol.

This short guide will help you alot if you know nothing about permissions nodes. Alot of plugin errors can be solved by correct perms setup 

In reference to your previous message:
- epiczones.\* (This is the wildcard node, for Administrators only – it allows people to create and change zones wherever they please)
- -epiczones.\* (This is a negated wildcard node, notice the extra hyphen)

For EpicZones – you do not need to give or take any nodes. People can still become owners if they have no EpicZones nodes.

The only person who needs EpicZones nodes of any kind (negated or not) is yourself; an admin on your server or someone with special privileges. Regular members need no EZ nodes.

Hope this helps.

**Comment by MozzVader** [comment]
I don't know how... but it is working just fine!!!
Thank you pal... you rock.
Sorry for making you work that hard lol!

**Comment by CourtArtanis** [comment]
No problem 

You know where we are if you have any other problems with EpicZones 

Cheers
